name: macOS

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu-build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-14, macos-15]
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{github.job}}-${{matrix.os}}
      - name: Prepare
        run: cmake -B build
      - name: Build
        # m1 machines have 3 CPU
        # Ref: https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners
        run: cmake --build build -j=3
      - name: Test
        run: ctest --output-on-failure --test-dir build